// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWvHL9kH-LFbtU_fEe8DA5nMoxP1KclzQ',
    appId: '1:185763981989:web:92d90419c5dfc7eb333b4c',
    messagingSenderId: '185763981989',
    projectId: 'notesonline-1f250',
    authDomain: 'notesonline-1f250.firebaseapp.com',
    storageBucket: 'notesonline-1f250.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFGHG9HcsBB3E36WwDudVJW3Tp-ZZQ9U',
    appId: '1:185763981989:android:33d9b19a96eb4515333b4c',
    messagingSenderId: '185763981989',
    projectId: 'notesonline-1f250',
    storageBucket: 'notesonline-1f250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqL2A7ZxtTUFCAbiXqT2k6gBMrNTGwP4g',
    appId: '1:185763981989:ios:6a3dfdca44b6305d333b4c',
    messagingSenderId: '185763981989',
    projectId: 'notesonline-1f250',
    storageBucket: 'notesonline-1f250.appspot.com',
    iosBundleId: 'com.example.notesonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqL2A7ZxtTUFCAbiXqT2k6gBMrNTGwP4g',
    appId: '1:185763981989:ios:6a3dfdca44b6305d333b4c',
    messagingSenderId: '185763981989',
    projectId: 'notesonline-1f250',
    storageBucket: 'notesonline-1f250.appspot.com',
    iosBundleId: 'com.example.notesonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWvHL9kH-LFbtU_fEe8DA5nMoxP1KclzQ',
    appId: '1:185763981989:web:e536e96b09a96186333b4c',
    messagingSenderId: '185763981989',
    projectId: 'notesonline-1f250',
    authDomain: 'notesonline-1f250.firebaseapp.com',
    storageBucket: 'notesonline-1f250.appspot.com',
  );
}
